version: '3.9'
services:
  postgresql:
    image: 'postgres'
    volumes: 
      - data:/var/lib/postgresql/data
    env_file: 
      - ./env/postgre.env
    healthcheck:
        test: ["CMD-SHELL", "pg_isready -U postgres"]
        interval: 10s
        timeout: 5s
        retries: 5
    ports: 
      - '5432:5432'
  server:
    build: ./server
    ports:
      - '8000:8000'
    volumes: 
      - ./server:/app
    depends_on: 
      - postgresql

volumes: 
  data: