version: '3.9'
services:
  postgresql:
    image: 'postgres:13.1-alpine'
    volumes: 
      - data:/var/lib/postgresql/data
    env_file: 
      - ./env/postgre.env
    healthcheck:
        test: ["CMD-SHELL", "pg_isready -U postgres"]
        interval: 10s
        timeout: 5s
        retries: 5
    ports: 
      - '5432:5432'
  redis:
    image: "redis"
    ports:
      - "6379:6379"
    volumes:
      - $PWD/redis-data:/var/lib/redis
  server:
    build:
      context: server
    ports:
      - '8000:8000'
    volumes: 
      - ./server:/app
    depends_on: 
      - "postgresql"
      - "redis"
  nginx:
    build:
      context: nginx
    image: nginx:stable-alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - "server"
      - "app"
  app :
    build:
      context: app
    image: "cirrusci/flutter:dev"
    volumes:
      - $PWD/app:/build
    ports:
      - "8080:8080"
    stdin_open: true
    tty: true
    depends_on:
      - "server"

volumes: 
  data: